create table public."Appointment" (
    id bigint generated by default as identity not null,
    school_id_number text not null,
    email text not null,
    full_name text not null,
    phone_number text not null,
    birth_date text not null,
    message text null,
    reason text not null,
    created_at timestamp with time zone not null default now(),
    constraint TryOut_pkey primary key (id)
) tablespace pg_default;