create table public."Inventory" (
    id bigint generated by default as identity not null,
    item_name text not null,
    item_qty numeric not null,
    constraint Inventory_pkey primary key (id)
) tablespace pg_default;