-- Create Inventory table
create table public."Inventory" (
    id bigint generated by default as identity not null,
    item_name text not null,
    item_qty numeric not null,
    constraint Inventory_pkey primary key (id)
) tablespace pg_default;

-- Create Appointment table
create table public."Appointment" (
    id bigint generated by default as identity not null,
    school_id_number text not null,
    email text not null,
    full_name text not null,
    phone_number text not null,
    birth_date text not null,
    message text null,
    reason text not null,
    created_at timestamp with time zone not null default now(),
    constraint Appointment_pkey primary key (id)
) tablespace pg_default;

-- Create TryOut table
create table public."TryOut" (
    id bigint generated by default as identity not null,
    school_id_number text not null,
    email text not null,
    full_name text not null,
    phone_number text not null,
    "degreeProgram" text not null,
    experience text not null,
    event text not null,
    course text not null,
    remarks text not null,
    recommendation text not null,
    created_at timestamp with time zone not null default now(),
    constraint TryOut_pkey primary key (id)
) tablespace pg_default; 